name: megatude

services:
  megatude:
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    ports:
      - "5555:5555"
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /
    healthcheck:
      test: ["CMD", "ping"]
