name: megatude deploy
run-name: ${{ github.actor }} is deploying to ${{ github.ref }}
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup openssh-client
        run: sudo apt-get install openssh-client

      - name: Prepare known host & private key
        run: |
          mkdir -p ~/.ssh;
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts;
          chmod 644 ~/.ssh/known_hosts;
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa;
          chmod 600 ~/.ssh/id_rsa;

      - name: SCP project files to server
        run: |
          rm -rf ./.git;
          echo "${{ secrets.CONFIG_YAML }}" > ./config.yaml;
          scp -i ~/.ssh/id_rsa -r . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }};

      - name: SSH into server and run docker compose up
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.SSH_PATH }}
            docker compose down
            APP_ARGS="-c ./config.yaml serve" docker compose up --force-recreate --build -d
          EOF
